# Generated by Django 3.1 on 2020-11-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digit_recognizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimageforhcr',
            name='image',
            field=models.ImageField(upload_to='images_hcr_api/'),
        ),
    ]
